/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef CGLM_BAKE_CONFIG_H
#define CGLM_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Convenience macro for exporting symbols */
#ifndef cglm_STATIC
#if cglm_EXPORTS && (defined(_MSC_VER) || defined(__MINGW32__))
  #define CGLM_EXPORT __declspec(dllexport)
#elif cglm_EXPORTS
  #define CGLM_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
  #define CGLM_EXPORT __declspec(dllimport)
#else
  #define CGLM_EXPORT
#endif
#else
  #define CGLM_EXPORT
#endif

#endif

